// World for an aggregator component.

package torvyn:aggregation@0.1.0;

/// World for a stream aggregator.
world stream-aggregator {
    import torvyn:streaming/types;
    import torvyn:streaming/buffer-allocator;

    export aggregator;
    export torvyn:streaming/lifecycle;
}
