//! SLSA-compatible build provenance generation and parsing.
//!
//! Per HLI Doc 08, Section 6.4. Phase 0 targets SLSA Level 1:
//! provenance exists, build process documented, generated by `torvyn pack`.
//!
//! The provenance record follows the in-toto Statement v1 format
//! with the SLSA Provenance v1 predicate.

use serde::{Deserialize, Serialize};
use time::OffsetDateTime;

// ---------------------------------------------------------------------------
// ProvenanceRecord
// ---------------------------------------------------------------------------

/// SLSA-compatible build provenance record.
///
/// Stored as `provenance.json` inside a `.torvyn` artifact.
///
/// # Invariants
/// - `subject_name` is non-empty.
/// - `subject_digest` is a valid SHA-256 hex string.
/// - `build_started <= build_finished`.
///
/// # Examples
/// ```
/// use torvyn_packaging::provenance::ProvenanceRecord;
///
/// let record = ProvenanceRecord::builder("my-transform", "sha256:abc123")
///     .source_repo("https://github.com/example/my-transform")
///     .torvyn_cli_version("0.3.0")
///     .build();
/// assert_eq!(record.subject_name, "my-transform");
/// ```
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ProvenanceRecord {
    /// Component name this provenance record covers.
    pub subject_name: String,

    /// SHA-256 digest of the artifact this record covers.
    /// Format: "sha256:{hex}"
    pub subject_digest: String,

    /// Build type URI (e.g., `https://torvyn.dev/build/v1`).
    pub build_type: String,

    /// Source information.
    pub source: SourceInfo,

    /// Builder information.
    pub builder: BuilderInfo,

    /// Build start timestamp (RFC 3339).
    pub build_started: String,

    /// Build finish timestamp (RFC 3339).
    pub build_finished: String,

    /// Internal build parameters.
    pub internal_params: BuildInternalParams,
}

/// Source code information.
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct SourceInfo {
    /// Source repository URL.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub repo: Option<String>,

    /// Git reference (e.g., "refs/tags/v1.2.0").
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub git_ref: Option<String>,

    /// Commit digest.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub commit_digest: Option<String>,
}

/// Builder identity.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct BuilderInfo {
    /// Builder identifier (e.g., "local", `https://github.com/actions/runner`).
    pub id: String,
}

impl Default for BuilderInfo {
    fn default() -> Self {
        Self {
            id: "local".to_owned(),
        }
    }
}

/// Internal build parameters — tool versions, WIT packages used.
#[derive(Clone, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct BuildInternalParams {
    /// Torvyn CLI version.
    pub torvyn_cli_version: String,

    /// Build tool name.
    #[serde(default)]
    pub build_tool: String,

    /// Build tool version.
    #[serde(default)]
    pub build_tool_version: String,

    /// Language version (e.g., Rust version).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub language_version: Option<String>,

    /// WIT packages compiled against.
    #[serde(default)]
    pub wit_packages: Vec<String>,
}

// ---------------------------------------------------------------------------
// In-toto envelope (full SLSA format)
// ---------------------------------------------------------------------------

/// Full SLSA in-toto Statement v1 envelope.
///
/// This is the JSON structure written to `provenance.json`.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct InTotoStatement {
    /// Statement type URI.
    #[serde(rename = "_type")]
    pub statement_type: String,

    /// Subjects covered by this statement.
    pub subject: Vec<InTotoSubject>,

    /// Predicate type URI.
    #[serde(rename = "predicateType")]
    pub predicate_type: String,

    /// SLSA provenance predicate.
    pub predicate: SlsaPredicate,
}

/// In-toto subject (the artifact being described).
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct InTotoSubject {
    /// Subject name.
    pub name: String,
    /// Subject digest map (algorithm → hex digest).
    pub digest: std::collections::BTreeMap<String, String>,
}

/// SLSA provenance v1 predicate.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct SlsaPredicate {
    /// Build definition.
    #[serde(rename = "buildDefinition")]
    pub build_definition: SlsaBuildDefinition,

    /// Run details.
    #[serde(rename = "runDetails")]
    pub run_details: SlsaRunDetails,
}

/// SLSA build definition.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct SlsaBuildDefinition {
    /// Build type URI.
    #[serde(rename = "buildType")]
    pub build_type: String,

    /// External parameters (source info).
    #[serde(rename = "externalParameters")]
    pub external_parameters: serde_json::Value,

    /// Internal parameters (tool versions).
    #[serde(rename = "internalParameters")]
    pub internal_parameters: serde_json::Value,
}

/// SLSA run details.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct SlsaRunDetails {
    /// Builder identity.
    pub builder: SlsaBuilder,
    /// Build metadata (timestamps).
    pub metadata: SlsaMetadata,
}

/// SLSA builder identity.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct SlsaBuilder {
    /// Builder identifier.
    pub id: String,
}

/// SLSA build metadata (timestamps).
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct SlsaMetadata {
    /// Invocation identifier.
    #[serde(
        rename = "invocationId",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub invocation_id: Option<String>,
    /// Build start timestamp (RFC 3339).
    #[serde(rename = "startedOn")]
    pub started_on: String,
    /// Build finish timestamp (RFC 3339).
    #[serde(rename = "finishedOn")]
    pub finished_on: String,
}

// ---------------------------------------------------------------------------
// Builder
// ---------------------------------------------------------------------------

/// Builder for constructing `ProvenanceRecord` values.
pub struct ProvenanceBuilder {
    record: ProvenanceRecord,
}

impl ProvenanceRecord {
    /// Start building a new provenance record.
    ///
    /// COLD PATH.
    pub fn builder(subject_name: &str, subject_digest: &str) -> ProvenanceBuilder {
        let now = OffsetDateTime::now_utc();
        let now_str = now
            .format(&time::format_description::well_known::Rfc3339)
            .unwrap_or_else(|_| "1970-01-01T00:00:00Z".to_owned());

        ProvenanceBuilder {
            record: ProvenanceRecord {
                subject_name: subject_name.to_owned(),
                subject_digest: subject_digest.to_owned(),
                build_type: "https://torvyn.dev/build/v1".to_owned(),
                source: SourceInfo::default(),
                builder: BuilderInfo::default(),
                build_started: now_str.clone(),
                build_finished: now_str,
                internal_params: BuildInternalParams::default(),
            },
        }
    }

    /// Convert this record to the full SLSA in-toto Statement JSON.
    ///
    /// # Errors
    /// Returns a serialization error if JSON encoding fails.
    ///
    /// COLD PATH.
    pub fn to_intoto_json(&self) -> Result<String, serde_json::Error> {
        let digest_value = self
            .subject_digest
            .strip_prefix("sha256:")
            .unwrap_or(&self.subject_digest);

        let mut digest_map = std::collections::BTreeMap::new();
        digest_map.insert("sha256".to_owned(), digest_value.to_owned());

        let external_params = serde_json::json!({
            "source_repo": self.source.repo,
            "source_ref": self.source.git_ref,
            "source_digest": self.source.commit_digest,
        });

        let internal_params = serde_json::json!({
            "torvyn_cli_version": self.internal_params.torvyn_cli_version,
            "build_tool": self.internal_params.build_tool,
            "build_tool_version": self.internal_params.build_tool_version,
            "language_version": self.internal_params.language_version,
            "wit_packages": self.internal_params.wit_packages,
        });

        let statement = InTotoStatement {
            statement_type: "https://in-toto.io/Statement/v1".to_owned(),
            subject: vec![InTotoSubject {
                name: self.subject_name.clone(),
                digest: digest_map,
            }],
            predicate_type: "https://slsa.dev/provenance/v1".to_owned(),
            predicate: SlsaPredicate {
                build_definition: SlsaBuildDefinition {
                    build_type: self.build_type.clone(),
                    external_parameters: external_params,
                    internal_parameters: internal_params,
                },
                run_details: SlsaRunDetails {
                    builder: SlsaBuilder {
                        id: self.builder.id.clone(),
                    },
                    metadata: SlsaMetadata {
                        invocation_id: None,
                        started_on: self.build_started.clone(),
                        finished_on: self.build_finished.clone(),
                    },
                },
            },
        };

        serde_json::to_string_pretty(&statement)
    }

    /// Parse a `ProvenanceRecord` from an in-toto Statement JSON string.
    ///
    /// # Errors
    /// Returns a deserialization error if JSON decoding fails.
    ///
    /// COLD PATH.
    pub fn from_intoto_json(json: &str) -> Result<Self, serde_json::Error> {
        let statement: InTotoStatement = serde_json::from_str(json)?;

        let subject = statement.subject.first();
        let subject_name = subject.map(|s| s.name.clone()).unwrap_or_default();
        let subject_digest = subject
            .and_then(|s| s.digest.get("sha256"))
            .map(|d| format!("sha256:{d}"))
            .unwrap_or_default();

        let ip = &statement.predicate.build_definition.internal_parameters;

        Ok(ProvenanceRecord {
            subject_name,
            subject_digest,
            build_type: statement.predicate.build_definition.build_type,
            source: SourceInfo {
                repo: statement
                    .predicate
                    .build_definition
                    .external_parameters
                    .get("source_repo")
                    .and_then(|v| v.as_str())
                    .map(|s| s.to_owned()),
                git_ref: statement
                    .predicate
                    .build_definition
                    .external_parameters
                    .get("source_ref")
                    .and_then(|v| v.as_str())
                    .map(|s| s.to_owned()),
                commit_digest: statement
                    .predicate
                    .build_definition
                    .external_parameters
                    .get("source_digest")
                    .and_then(|v| v.as_str())
                    .map(|s| s.to_owned()),
            },
            builder: BuilderInfo {
                id: statement.predicate.run_details.builder.id,
            },
            build_started: statement.predicate.run_details.metadata.started_on,
            build_finished: statement.predicate.run_details.metadata.finished_on,
            internal_params: BuildInternalParams {
                torvyn_cli_version: ip
                    .get("torvyn_cli_version")
                    .and_then(|v| v.as_str())
                    .unwrap_or("")
                    .to_owned(),
                build_tool: ip
                    .get("build_tool")
                    .and_then(|v| v.as_str())
                    .unwrap_or("")
                    .to_owned(),
                build_tool_version: ip
                    .get("build_tool_version")
                    .and_then(|v| v.as_str())
                    .unwrap_or("")
                    .to_owned(),
                language_version: ip
                    .get("language_version")
                    .and_then(|v| v.as_str())
                    .map(|s| s.to_owned()),
                wit_packages: ip
                    .get("wit_packages")
                    .and_then(|v| v.as_array())
                    .map(|arr| {
                        arr.iter()
                            .filter_map(|v| v.as_str().map(|s| s.to_owned()))
                            .collect()
                    })
                    .unwrap_or_default(),
            },
        })
    }
}

impl ProvenanceBuilder {
    /// Set the source repository URL.
    pub fn source_repo(mut self, repo: &str) -> Self {
        self.record.source.repo = Some(repo.to_owned());
        self
    }

    /// Set the git reference.
    pub fn source_ref(mut self, git_ref: &str) -> Self {
        self.record.source.git_ref = Some(git_ref.to_owned());
        self
    }

    /// Set the commit digest.
    pub fn commit_digest(mut self, digest: &str) -> Self {
        self.record.source.commit_digest = Some(digest.to_owned());
        self
    }

    /// Set the builder identifier.
    pub fn builder_id(mut self, id: &str) -> Self {
        self.record.builder.id = id.to_owned();
        self
    }

    /// Set the Torvyn CLI version.
    pub fn torvyn_cli_version(mut self, version: &str) -> Self {
        self.record.internal_params.torvyn_cli_version = version.to_owned();
        self
    }

    /// Set the build tool name and version.
    pub fn build_tool(mut self, tool: &str, version: &str) -> Self {
        self.record.internal_params.build_tool = tool.to_owned();
        self.record.internal_params.build_tool_version = version.to_owned();
        self
    }

    /// Set the language version.
    pub fn language_version(mut self, version: &str) -> Self {
        self.record.internal_params.language_version = Some(version.to_owned());
        self
    }

    /// Set the WIT packages compiled against.
    pub fn wit_packages(mut self, packages: Vec<String>) -> Self {
        self.record.internal_params.wit_packages = packages;
        self
    }

    /// Set explicit build start and finish timestamps.
    pub fn build_timestamps(mut self, started: &str, finished: &str) -> Self {
        self.record.build_started = started.to_owned();
        self.record.build_finished = finished.to_owned();
        self
    }

    /// Consume the builder and return the finished `ProvenanceRecord`.
    pub fn build(self) -> ProvenanceRecord {
        self.record
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn builder_creates_record() {
        let r = ProvenanceRecord::builder("test-comp", "sha256:abc123")
            .source_repo("https://github.com/example/test")
            .torvyn_cli_version("0.3.0")
            .build_tool("cargo-component", "0.20.0")
            .language_version("1.80.0")
            .wit_packages(vec!["torvyn:streaming@0.1.0".into()])
            .build();

        assert_eq!(r.subject_name, "test-comp");
        assert_eq!(r.subject_digest, "sha256:abc123");
        assert_eq!(
            r.source.repo.as_deref(),
            Some("https://github.com/example/test")
        );
        assert_eq!(r.internal_params.torvyn_cli_version, "0.3.0");
        assert_eq!(r.internal_params.build_tool, "cargo-component");
        assert_eq!(
            r.internal_params.wit_packages,
            vec!["torvyn:streaming@0.1.0"]
        );
    }

    #[test]
    fn intoto_json_roundtrip() {
        let original = ProvenanceRecord::builder("my-comp", "sha256:deadbeef")
            .source_repo("https://github.com/example/my-comp")
            .torvyn_cli_version("0.3.0")
            .build_timestamps("2026-03-11T12:00:00Z", "2026-03-11T12:02:30Z")
            .build();

        let json = original.to_intoto_json().unwrap();

        // Verify the JSON contains expected SLSA fields.
        assert!(json.contains("https://in-toto.io/Statement/v1"));
        assert!(json.contains("https://slsa.dev/provenance/v1"));
        assert!(json.contains("deadbeef"));

        let parsed = ProvenanceRecord::from_intoto_json(&json).unwrap();
        assert_eq!(parsed.subject_name, "my-comp");
        assert_eq!(parsed.subject_digest, "sha256:deadbeef");
        assert_eq!(parsed.build_started, "2026-03-11T12:00:00Z");
    }

    #[test]
    fn default_builder_is_local() {
        let r = ProvenanceRecord::builder("x", "sha256:000").build();
        assert_eq!(r.builder.id, "local");
    }

    #[test]
    fn default_build_type_is_torvyn() {
        let r = ProvenanceRecord::builder("x", "sha256:000").build();
        assert_eq!(r.build_type, "https://torvyn.dev/build/v1");
    }
}
