//! Echo source: produces N numbered elements through the real
//! buffer-allocator path so the host's `DefaultResourceManager` sees one
//! `ComponentToHost` copy event per element.
//!
//! Configuration (JSON string via `lifecycle.init`):
//! ```json
//! { "count": 100 }
//! { "count": 100, "payload_bytes": 4096 }
//! ```
//!
//! - `count` — number of elements to produce. Absent or unparsable falls
//!   back to 1000.
//! - `payload_bytes` — size of each element's payload. Defaults to 8: the
//!   little-endian sequence number and nothing else, which is the shape the
//!   copy-accounting end-to-end test asserts against. Values below 8 are
//!   clamped up so the sequence number always fits.
//!
//! Whatever the size, the payload is written with a single `write` call, so
//! the host records exactly one `ComponentToHost` copy of exactly
//! `payload_bytes` bytes per element. The first eight bytes always carry the
//! sequence number; the remainder is a fixed filler pattern, so payload
//! content is deterministic and a benchmark sweeping `payload_bytes`
//! measures copy cost rather than data generation.

#[allow(warnings)]
mod bindings;

use std::cell::RefCell;

use bindings::exports::torvyn::streaming::{lifecycle, source};
use bindings::torvyn::streaming::buffer_allocator::allocate;
use bindings::torvyn::streaming::types::{
    BackpressureSignal, ElementMeta, OutputElement, ProcessError,
};

/// Element count used when `init` receives an empty or unparsable config.
const DEFAULT_COUNT: u64 = 1000;

/// Payload size used when the config does not specify `payload_bytes`.
/// Eight bytes is exactly the little-endian sequence number, which is what
/// the copy-accounting invariant test expects.
const DEFAULT_PAYLOAD_BYTES: u64 = 8;

/// Width of the little-endian sequence number written at offset 0. Also the
/// floor for `payload_bytes`.
const SEQUENCE_BYTES: usize = 8;

/// Upper bound on `payload_bytes`, matching the host's per-buffer capacity
/// ceiling (16 MiB). Oversized requests are clamped rather than rejected so
/// a mis-typed config degrades instead of failing the whole flow.
const MAX_PAYLOAD_BYTES: u64 = 16 * 1024 * 1024;

/// Filler byte written to payload positions past the sequence number.
const FILLER: u8 = 0xA5;

struct EchoSource;

thread_local! {
    static STATE: RefCell<State> = const {
        RefCell::new(State {
            remaining: 0,
            sequence: 0,
            payload: Vec::new(),
        })
    };
}

struct State {
    remaining: u64,
    sequence: u64,
    /// Reusable payload scratch, sized once in `init` and reused by every
    /// `pull`, so the guest performs no per-element allocation and the
    /// measured cost is the buffer write itself.
    payload: Vec<u8>,
}

/// Extract an unsigned integer field from a flat JSON object.
///
/// Deliberately minimal: this fixture's configs are generated by the test
/// and benchmark harnesses, are always flat, and are always integer-valued,
/// so a full JSON parser would be dead weight in a Wasm guest. Returns
/// `None` when the key is absent or its value is not a run of ASCII digits.
fn json_u64_field(config: &str, key: &str) -> Option<u64> {
    let mut needle = String::with_capacity(key.len() + 2);
    needle.push('"');
    needle.push_str(key);
    needle.push('"');

    let key_at = config.find(&needle)?;
    let after_key = &config[key_at + needle.len()..];
    let after_colon = after_key.trim_start().strip_prefix(':')?.trim_start();

    let digits: String = after_colon
        .chars()
        .take_while(char::is_ascii_digit)
        .collect();
    if digits.is_empty() {
        None
    } else {
        digits.parse().ok()
    }
}

impl lifecycle::Guest for EchoSource {
    fn init(config: String) -> Result<(), ProcessError> {
        let count = json_u64_field(&config, "count").unwrap_or(DEFAULT_COUNT);
        let payload_bytes = json_u64_field(&config, "payload_bytes")
            .unwrap_or(DEFAULT_PAYLOAD_BYTES)
            .clamp(SEQUENCE_BYTES as u64, MAX_PAYLOAD_BYTES);

        // Lossless on wasm32: `payload_bytes` is clamped to 16 MiB above.
        let payload_len = payload_bytes as usize;

        STATE.with(|s| {
            let mut state = s.borrow_mut();
            state.remaining = count;
            state.sequence = 0;
            state.payload = vec![FILLER; payload_len];
        });

        Ok(())
    }

    fn teardown() {}
}

impl source::Guest for EchoSource {
    fn pull() -> Result<Option<OutputElement>, ProcessError> {
        // Claim a sequence number and stamp it into the reusable payload in
        // a single borrow, so the fast path touches the thread-local once.
        let Some((seq, capacity)) = STATE.with(|s| {
            let mut state = s.borrow_mut();
            if state.remaining == 0 {
                return None;
            }
            let seq = state.sequence;
            state.sequence += 1;
            state.remaining -= 1;
            state.payload[..SEQUENCE_BYTES].copy_from_slice(&seq.to_le_bytes());
            Some((seq, state.payload.len() as u64))
        }) else {
            return Ok(None);
        };

        let mb =
            allocate(capacity).map_err(|_| ProcessError::Internal("allocate failed".into()))?;
        STATE.with(|s| {
            mb.write(0, &s.borrow().payload)
                .map_err(|_| ProcessError::Internal("write failed".into()))
        })?;
        let buf = mb.freeze();

        Ok(Some(OutputElement {
            meta: ElementMeta {
                sequence: seq,
                timestamp_ns: 0,
                content_type: "application/octet-stream".into(),
            },
            payload: buf,
        }))
    }

    fn notify_backpressure(_signal: BackpressureSignal) {}
}

bindings::export!(EchoSource with_types_in bindings);
