package torvyn:streaming@0.1.0;

world transform {
    import types;
    import buffer-allocator;

    export processor;
}

world managed-transform {
    import types;
    import buffer-allocator;

    export processor;
    export lifecycle;
}

world data-source {
    import types;
    import buffer-allocator;

    export source;
    export lifecycle;
}

world data-sink {
    import types;

    export sink;
    export lifecycle;
}
